name: Update site-data.json from Issue

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  issues: write

jobs:
  update:
    if: contains(github.event.issue.title, 'US-SITE-DATA update')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decode payload from issue body
        id: decode
        run: |
          BODY=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")
          # body is base64 JSON string from the site
          echo "$BODY" | base64 --decode > content/site-data.json
          echo "decoded=true" >> $GITHUB_OUTPUT

      - name: Commit & push
        if: steps.decode.outputs.decoded == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content/site-data.json
          git commit -m "Update site-data.json from issue #${{ github.event.issue.number }}" || echo "No changes"
          git push

      - name: Comment on issue
        run: |
          gh issue comment ${{ github.event.issue.number }} -b "✅ site-data.json updated!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

